apiVersion: v1
kind: Pod
metadata:
  name: cvmfs-cms
spec:
  containers:
   - name: shell
     image: "almalinux:8.10"
     # image: "centos:7"
     # image: "quay.io/jupyter/base-notebook"
     imagePullPolicy: IfNotPresent
     command: ["/bin/sh", "-c", "sleep infinity"]
     volumeMounts:
       - name: cvmfs-mount
         subPath: cms.cern.ch
         mountPath: /cvmfs/cms.cern.ch
         mountPropagation: HostToContainer
  volumes:
   - name: cvmfs-mount
     persistentVolumeClaim:
       claimName: cvmfs
